<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';use VP3\Projects\ProjectService;$customer=vp3_require_customer();$id=(int)vp3_input('id');$project=vp3_project_access($id,(int)$customer['id']);if(!$project){http_response_code(404);exit('Project not found.');}
$service=new ProjectService(vp3_db());
if(vp3_method()==='POST'){vp3_verify_csrf();$action=vp3_input('action');try{if($action==='task_status')$service->customerTaskStatus((int)vp3_input('task_id'),(int)$customer['id'],vp3_input('status'));elseif($action==='approval')$service->respondApproval((int)vp3_input('approval_id'),(int)$customer['id'],vp3_input('status'),vp3_input('response_notes'));elseif($action==='comment'){if(vp3_text_length(vp3_input('comment'))<2)throw new RuntimeException('comment_required');vp3_db()->prepare("INSERT INTO project_comments (project_id,author_type,author_id,visibility,comment,created_at,updated_at) VALUES (?,'customer',?,'shared',?,NOW(),NOW())")->execute([$id,$customer['id'],vp3_input('comment')]);$service->activity($id,'customer',(int)$customer['id'],'comment.created','project',$project['project_uuid'],'Customer added a project comment.');}elseif($action==='asset'){$service->registerAsset($id,(int)$customer['id'],$_POST);}vp3_flash('success','Project updated.');}catch(Throwable $e){vp3_flash('error',str_replace('_',' ',$e->getMessage()));}vp3_redirect('account-project.php?id='.$id);}
$milestones=$tasks=$approvals=$assets=$comments=$activity=[];
$stmt=vp3_db()->prepare('SELECT * FROM project_milestones WHERE project_id=? ORDER BY sort_order,due_date,id');$stmt->execute([$id]);$milestones=$stmt->fetchAll();
$stmt=vp3_db()->prepare('SELECT t.*,m.title milestone_title FROM project_tasks t LEFT JOIN project_milestones m ON m.id=t.milestone_id WHERE t.project_id=? ORDER BY FIELD(t.status,\'in_progress\',\'ready\',\'waiting\',\'review\',\'backlog\',\'completed\',\'cancelled\'),t.due_at,t.sort_order');$stmt->execute([$id]);$tasks=$stmt->fetchAll();
$stmt=vp3_db()->prepare('SELECT * FROM project_approvals WHERE project_id=? AND requested_from_customer_id=? ORDER BY FIELD(status,\'pending\',\'revision_requested\',\'approved\',\'rejected\',\'cancelled\'),created_at DESC');$stmt->execute([$id,$customer['id']]);$approvals=$stmt->fetchAll();
$stmt=vp3_db()->prepare("SELECT * FROM project_assets WHERE project_id=? AND visibility IN ('customer','shared') AND status='active' ORDER BY updated_at DESC");$stmt->execute([$id]);$assets=$stmt->fetchAll();
$stmt=vp3_db()->prepare("SELECT * FROM project_comments WHERE project_id=? AND visibility IN ('customer','shared') ORDER BY created_at DESC LIMIT 50");$stmt->execute([$id]);$comments=$stmt->fetchAll();
$stmt=vp3_db()->prepare('SELECT * FROM project_activity WHERE project_id=? ORDER BY created_at DESC LIMIT 25');$stmt->execute([$id]);$activity=$stmt->fetchAll();
$pageTitle=$project['title'];require VP3_ROOT.'/includes/account-header.php';?>
<div class="project-hero"><div><span class="eyebrow"><?=vp3_e(vp3_project_phase_label($project['phase']))?></span><h1><?=vp3_e($project['title'])?></h1><p><?=vp3_e($project['summary'])?></p><div class="project-hero-meta"><span><?=vp3_e(str_replace('_',' ',$project['health_status']))?></span><span>Target: <?=vp3_e($project['target_launch_date']?:'Not scheduled')?></span></div></div><div class="readiness-ring" style="--progress:<?=(int)$project['readiness_percent']?>"><strong><?=(int)$project['readiness_percent']?>%</strong><span>launch ready</span></div></div>
<section class="workspace-tabs"><a href="#tasks">Tasks</a><a href="#approvals">Approvals</a><a href="#assets">Assets</a><a href="#activity">Activity</a></section>
<section id="tasks" class="section compact-section"><div class="section-heading"><div><span class="eyebrow">Action plan</span><h2>Tasks and milestones</h2></div></div><div class="milestone-list"><?php foreach($milestones as $m):?><article><span class="badge <?=vp3_e($m['status'])?>"><?=vp3_e($m['status'])?></span><h3><?=vp3_e($m['title'])?></h3><p><?=vp3_e($m['description'])?></p><small><?=vp3_e($m['due_date']?:'No due date')?></small></article><?php endforeach;?></div><div class="task-list"><?php foreach($tasks as $t):?><article class="task-row <?=vp3_e(vp3_due_state($t['due_at']))?>"><div><span class="badge <?=vp3_e($t['status'])?>"><?=vp3_e(str_replace('_',' ',$t['status']))?></span><h3><?=vp3_e($t['title'])?></h3><p><?=vp3_e($t['description'])?></p><small><?=vp3_e($t['milestone_title']?:'General')?> · <?=vp3_e($t['due_at']?:'No due date')?></small></div><?php if((int)$t['assigned_customer_id']===(int)$customer['id']&&!in_array($t['status'],['completed','cancelled'],true)):?><form method="post"><?=vp3_csrf_field()?><input type="hidden" name="action" value="task_status"><input type="hidden" name="task_id" value="<?=(int)$t['id']?>"><select name="status"><option value="in_progress">In progress</option><option value="waiting">Waiting</option><option value="review">Ready for review</option><option value="completed">Completed</option></select><button class="button small">Update</button></form><?php else:?><span><?=vp3_e($t['assigned_customer_id']?'Your task':'VP3 task')?></span><?php endif;?></article><?php endforeach;?><?php if(!$tasks):?><div class="empty-state"><p>No tasks have been added yet.</p></div><?php endif;?></div></section>
<section id="approvals" class="section compact-section"><div class="section-heading"><div><span class="eyebrow">Decisions</span><h2>Approvals</h2></div></div><div class="approval-grid"><?php foreach($approvals as $a):?><article class="card"><span class="badge <?=vp3_e($a['status'])?>"><?=vp3_e(str_replace('_',' ',$a['status']))?></span><h3><?=vp3_e($a['title'])?></h3><p><?=vp3_e($a['instructions'])?></p><?php if($a['status']==='pending'):?><form method="post"><?=vp3_csrf_field()?><input type="hidden" name="action" value="approval"><input type="hidden" name="approval_id" value="<?=(int)$a['id']?>"><div class="field"><label>Response notes</label><textarea name="response_notes"></textarea></div><div class="form-actions"><button class="button small" name="status" value="approved">Approve</button><button class="button small secondary" name="status" value="revision_requested">Request revision</button><button class="button small danger" name="status" value="rejected">Reject</button></div></form><?php elseif($a['response_notes']):?><p><strong>Your response:</strong> <?=vp3_e($a['response_notes'])?></p><?php endif;?></article><?php endforeach;?><?php if(!$approvals):?><div class="empty-state"><p>No approvals are waiting.</p></div><?php endif;?></div></section>
<section id="assets" class="section compact-section"><div class="section-heading"><div><span class="eyebrow">Shared library</span><h2>Project assets</h2></div></div><div class="admin-split"><div class="asset-grid"><?php foreach($assets as $asset):?><article class="asset-card"><span><?=vp3_e($asset['category'])?></span><h3><?=vp3_e($asset['title'])?></h3><p><?=vp3_e($asset['description'])?></p><small>v<?=(int)$asset['version_number']?> · <?=vp3_e(str_replace('_',' ',$asset['approval_status']))?></small><?php if($url=vp3_public_https_url($asset['external_url'])):?><a class="button small secondary" href="<?=vp3_e($url)?>" rel="noopener noreferrer" target="_blank">Open asset</a><?php endif;?></article><?php endforeach;?></div><form class="card" method="post"><?=vp3_csrf_field()?><input type="hidden" name="action" value="asset"><h3>Register an external asset</h3><p class="helper">Foundation v1 stores secure metadata and HTTPS references. Direct uploads will use a storage-provider adapter in a later phase.</p><div class="field"><label>Title</label><input name="title" required></div><div class="field"><label>Category</label><select name="category"><option>general</option><option>brand</option><option>artwork</option><option>audio</option><option>video</option><option>script</option><option>contract</option><option>launch</option></select></div><div class="field"><label>HTTPS URL</label><input name="external_url" type="url" required></div><div class="field"><label>Description</label><textarea name="description"></textarea></div><button class="button small">Register asset</button></form></div></section>
<section id="activity" class="section compact-section"><div class="admin-split"><div><span class="eyebrow">Conversation</span><h2>Project comments</h2><form class="card" method="post"><?=vp3_csrf_field()?><input type="hidden" name="action" value="comment"><div class="field"><label>Add a comment</label><textarea name="comment" required></textarea></div><button class="button small">Post comment</button></form><div class="activity-list"><?php foreach($comments as $c):?><article><strong><?=vp3_e(ucfirst($c['author_type']))?></strong><span><?=vp3_e($c['created_at'])?></span><p><?=nl2br(vp3_e($c['comment']))?></p></article><?php endforeach;?></div></div><div><span class="eyebrow">Timeline</span><h2>Recent activity</h2><div class="activity-list"><?php foreach($activity as $item):?><article><strong><?=vp3_e($item['summary'])?></strong><span><?=vp3_e($item['created_at'])?></span></article><?php endforeach;?></div></div></div></section>
<?php require VP3_ROOT.'/includes/account-footer.php'; ?>
