<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
$pageTitle='Pricing and Launch Options';
$pageDescription='Compare VP3 self-hosted licensing, managed hosting, and full-service creative launch options.';
$bodyClass='pricing-page';
require VP3_ROOT.'/includes/header.php';
?>
<section class="subpage-hero pricing-hero">
  <div><span class="eyebrow">Flexible ownership</span><h1>Choose the launch model that fits your story.</h1><p>Start with licensed software, a fully managed hosted platform, or a custom creative and operational partnership. Final pricing is configured around product edition, audience scale, support level, and launch scope.</p><div class="hero-actions"><a class="button" href="#plans">Compare plans</a><a class="button ghost" href="contact.php">Talk to sales</a></div></div>
  <div class="subpage-hero-art"><img src="<?=vp3_e(vp3_url('assets/images/site/pricing-hosting-options.svg'))?>" alt="Self-hosted licensing and VP3-hosted service options"></div>
</section>
<section class="narrative-section pricing-section" id="plans">
  <div class="section-kicker">Platform options</div><div class="split-heading"><h2>Own the product. <span>Choose the service level.</span></h2><p>Each option keeps the platform organized around your brand. The difference is how much infrastructure, installation, support, and ongoing production help VP3 provides.</p></div>
  <div class="pricing-grid">
    <article class="price-plan"><span class="plan-label">Self-hosted license</span><h3>Licensed ownership</h3><div class="price">Custom quote</div><p>For teams with their own hosting environment or technical partner.</p><ul class="list"><li>One-time product license structure</li><li>Authorized domain activation</li><li>Guided installation workflow</li><li>Defined update eligibility</li><li>Customer-managed infrastructure</li></ul><a class="button secondary" href="checkout.php?plan=self-hosted">Choose self-hosted</a></article>
    <article class="price-plan featured"><span class="plan-label">VP3 hosted</span><div class="popular">Recommended</div><h3>Managed platform launch</h3><div class="price">Custom monthly</div><p>For storytellers who want to focus on content while VP3 manages the environment.</p><ul class="list"><li>Licensed hosted product</li><li>VP3 subdomain or custom domain</li><li>One-click installation workflow</li><li>Monitoring and version visibility</li><li>Managed updates and support</li></ul><a class="button" href="checkout.php?plan=hosted">Choose VP3 hosted</a></article>
    <article class="price-plan"><span class="plan-label">Creative partnership</span><h3>Platform + full service</h3><div class="price">Custom engagement</div><p>For launches that need story development, production organization, campaign support, and hands-on guidance.</p><ul class="list"><li>Creative discovery and content planning</li><li>Writing and story development</li><li>AI-assisted production management</li><li>Launch campaign and audience workflow</li><li>Priority setup and ongoing support</li></ul><a class="button secondary" href="contact.php">Plan a custom launch</a></article>
  </div>
</section>
<section class="comparison-section"><div class="section-kicker">Side-by-side</div><h2>What changes between options?</h2><div class="comparison modern"><div class="comparison-row"><div>Service</div><div>Self-hosted</div><div>VP3 hosted</div><div>Creative partnership</div></div><div class="comparison-row"><div>Product license</div><div>Included</div><div>Included</div><div>Included</div></div><div class="comparison-row"><div>Infrastructure</div><div>Customer managed</div><div>VP3 managed</div><div>VP3 managed</div></div><div class="comparison-row"><div>Installation</div><div>Guided</div><div>Managed workflow</div><div>Managed priority launch</div></div><div class="comparison-row"><div>Creative planning</div><div>Optional</div><div>Optional</div><div>Included</div></div><div class="comparison-row"><div>AI production management</div><div>Platform tools</div><div>Platform tools</div><div>Tools + guided workflow</div></div><div class="comparison-row"><div>Support</div><div>Standard</div><div>Managed</div><div>Priority partnership</div></div></div></section>
<section class="faq-section"><div class="section-kicker">Common questions</div><div class="faq-grid"><article><h3>Why are prices configured?</h3><p>VP3 supports multiple product editions, hosting requirements, audience sizes, support levels, and creative service scopes. A configured quote prevents a one-size-fits-all plan from limiting the launch.</p></article><article><h3>Can I move from self-hosted to VP3 hosted?</h3><p>The architecture is designed around product, license, release, and hosting records, allowing a future migration path without rebuilding the entire account relationship.</p></article><article><h3>Is creative support required?</h3><p>No. The platform can be licensed or hosted by itself. Full-service support is available when you want help shaping the story, planning releases, or managing the production rhythm.</p></article></div></section>
<section class="final-story-cta"><span class="eyebrow">Need the right scope?</span><h2>Let’s design the launch around your project.</h2><p>Tell us what you are creating, what is ready, and where you need support.</p><div class="hero-actions"><a class="button" href="contact.php">Request a launch plan</a><a class="button ghost" href="signup.php">Create an account</a></div></section>
<?php require VP3_ROOT.'/includes/footer.php'; ?>
