<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';
$pageTitle='Creative Services';
$pageDescription='VP3 combines story development, platform production, launch planning, and ongoing creative operations for creators and entertainment brands.';
$packages=vp3_service_packages(true);
require VP3_ROOT.'/includes/header.php';
?>
<section class="services-hero"><div><span class="eyebrow">From concept to continuous release</span><h1>Build the story.<br><span>Run the experience.</span></h1><p>VP3 combines full-service creative support with the operating system behind your media platform. Start with a focused launch engagement or build an ongoing production relationship.</p><div class="hero-actions"><a class="button" href="<?=vp3_e(vp3_url('book-demo.php'))?>">Book a discovery call</a><a class="button ghost" href="#packages">Explore services</a></div></div><div class="service-process"><span>01</span><b>Discover</b><i></i><span>02</span><b>Plan</b><i></i><span>03</span><b>Produce</b><i></i><span>04</span><b>Launch</b></div></section>
<section class="section narrative-section"><div class="split-heading"><div><span class="section-kicker">A creative operating partner</span><h2>Your audience sees the story.<br><span>VP3 manages the system behind it.</span></h2></div><p>Story development, content writing, release planning, platform setup, approvals, and ongoing production management live inside one connected client workflow.</p></div><div class="grid three"><article class="card"><span class="card-number">01</span><h3>Story and content development</h3><p>Clarify the concept, audience, series structure, release language, and content needed to make the experience understandable and compelling.</p></article><article class="card"><span class="card-number">02</span><h3>Production and launch management</h3><p>Turn the concept into milestones, responsibilities, approvals, launch gates, and an operating calendar that keeps the work moving.</p></article><article class="card"><span class="card-number">03</span><h3>Platform and audience experience</h3><p>Configure the branded destination where episodes, music, memberships, merchandise, community, and releases become one owned world.</p></article></div></section>
<section id="packages" class="section dark"><div class="section-head"><span class="eyebrow">Service packages</span><h2>Start with the level of support your story needs.</h2><p>Packages are configurable in the VP3 administration console and can be combined into a custom proposal.</p></div><div class="service-package-grid"><?php foreach($packages as $package):$items=$package['items']??[];?><article class="service-package-card"><span class="package-category"><?=vp3_e(ucwords(str_replace('_',' ',(string)($package['category']??'creative'))))?></span><h3><?=vp3_e($package['name'])?></h3><p><?=vp3_e($package['short_description']??$package['description']??'')?></p><strong class="package-price"><?=((int)($package['price_cents']??0)>0)?vp3_e(vp3_money((int)$package['price_cents'])):'Custom proposal'?><?php if(($package['billing_type']??'')==='monthly'):?><small>/ month</small><?php endif;?></strong><ul><?php foreach($items as $item):?><li><?=vp3_e(is_array($item)?($item['label']??''):$item)?></li><?php endforeach;?></ul><a class="button small" href="<?=vp3_e(vp3_url('book-demo.php?service='.urlencode((string)$package['name'])))?>">Discuss this service</a></article><?php endforeach;?></div></section>
<section class="section"><div class="cta"><div><span class="eyebrow">Bring the idea</span><h2>We will help turn it into an organized, owned media experience.</h2><p>Start with a discovery conversation and a structured creative brief.</p></div><a class="button" href="<?=vp3_e(vp3_url('book-demo.php'))?>">Book a discovery call</a></div></section>
<?php require VP3_ROOT.'/includes/footer.php'; ?>
