<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';$viewer=vp3_require_viewer();
if(vp3_method()==='POST'){vp3_verify_csrf();$action=vp3_input('action');if($action==='revoke_devices'){vp3_db()->prepare('DELETE FROM viewer_remember_tokens WHERE viewer_id=?')->execute([(int)$viewer['id']]);vp3_flash('success','Remembered viewer devices were signed out.');}vp3_redirect('viewer-settings.php');}
$pageTitle='Viewer Settings';$pageDescription='Update your viewer profile, privacy preference, remembered devices, and account data.';require VP3_ROOT.'/includes/viewer-header.php';$devices=vp3_db()->prepare('SELECT token_uuid,last_used_at,created_at,expires_at FROM viewer_remember_tokens WHERE viewer_id=? ORDER BY created_at DESC');$devices->execute([(int)$viewer['id']]);$devices=$devices->fetchAll();?>
<section class="card viewer-settings-card"><h2>Profile</h2><form data-viewer-profile-form><div class="field-row"><div class="field"><label>Display name<input name="display_name" maxlength="150" required value="<?=vp3_e($viewer['display_name'])?>"></label></div><div class="field"><label>Handle<input name="handle" maxlength="30" pattern="[a-z0-9_]{3,30}" required value="<?=vp3_e($viewer['handle'])?>"></label></div></div><div class="field"><label>Bio<textarea name="bio" maxlength="500"><?=vp3_e((string)$viewer['bio'])?></textarea></label></div><div class="field"><label>Profile visibility<select name="profile_visibility"><option value="public" <?=$viewer['profile_visibility']==='public'?'selected':''?>>Public</option><option value="private" <?=$viewer['profile_visibility']==='private'?'selected':''?>>Private</option></select></label></div><button class="button">Save viewer profile</button><p class="helper" data-viewer-profile-status></p></form></section>
<section class="card viewer-settings-card"><h2>Remembered devices</h2><p><?=count($devices)?> remembered sign-in<?=count($devices)===1?'':'s'?>. Current browser sessions remain active until sign-out.</p><form method="post"><?=vp3_csrf_field()?><input type="hidden" name="action" value="revoke_devices"><button class="button secondary">Sign out remembered devices</button></form></section>
<section class="card viewer-settings-card"><h2>Your data</h2><p>Download a JSON copy of your profile, follows, saved/liked clips, and watch history.</p><a class="button secondary" href="viewer-export.php">Download viewer data</a></section>
<section class="card viewer-settings-card danger-zone"><h2>Delete viewer account</h2><p>This permanently deletes the viewer profile, follows, saved clips, likes, and viewer watch library. It does not affect a separate VP3 creator/customer account.</p><form method="post" action="viewer-delete.php"><?=vp3_csrf_field()?><div class="field"><label>Confirm password<input type="password" name="password" required autocomplete="current-password"></label></div><button class="button secondary" data-confirm="Delete this viewer account permanently?">Delete viewer account</button></form></section>
<?php require VP3_ROOT.'/includes/viewer-footer.php';?>
