<?php
declare(strict_types=1);require __DIR__.'/bootstrap.php';use VP3\Mail\MailerFactory;
$error='';
if(vp3_method()==='POST'){
 vp3_verify_csrf();$name=trim(vp3_input('display_name'));$handle=strtolower(trim(vp3_input('handle')));$email=strtolower(trim(vp3_input('email')));$password=(string)($_POST['password']??'');
 if($name===''||strlen($name)>150||!preg_match('/^[a-z0-9_]{3,30}$/',$handle)||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<12){$error='Use a valid name, handle, email, and password of at least 12 characters.';}
 elseif(!vp3_db_available()){$error='Database configuration is required before viewer account creation.';}
 elseif(!vp3_rate_limit('viewer-signup:'.$email,4,3600)){$error='Too many signup attempts. Try again later.';}
 else{try{$token=vp3_secure_token();$viewerId=vp3_transaction(function(PDO $db)use($name,$handle,$email,$password,$token):int{$stmt=$db->prepare("INSERT INTO viewer_accounts (viewer_uuid,email,password_hash,display_name,handle,status,created_at,updated_at) VALUES (?,?,?,?,?,'pending',NOW(),NOW())");$stmt->execute([vp3_uuid(),$email,password_hash($password,PASSWORD_DEFAULT),$name,$handle]);$id=(int)$db->lastInsertId();$db->prepare('INSERT INTO viewer_email_verifications (viewer_id,token_hash,expires_at,created_at) VALUES (?,?,DATE_ADD(NOW(),INTERVAL 24 HOUR),NOW())')->execute([$id,vp3_hash_token($token)]);return$id;});$url=vp3_url('viewer-verify-email.php?token='.rawurlencode($token));MailerFactory::make()->send($email,'Verify your VP3 viewer account',"Verify your viewer account: {$url}\n\nThis link expires in 24 hours.");vp3_audit('viewer',$viewerId,'viewer.registered','viewer',(string)$viewerId);$_SESSION['viewer_verification_email']=$email;vp3_redirect('viewer-verification-pending.php');}catch(PDOException $e){$error=$e->getCode()==='23000'?'That email or handle is already in use.':'Viewer account creation failed.';vp3_log('error','Viewer signup failed',['code'=>$e->getCode()]);}}
}
$pageTitle='Create Viewer Account';$pageDescription='Follow creators, save clips, and build your personalized VP3 Reels feed.';$bodyClass='auth-page viewer-auth-page';$extraStyles=['assets/css/reels.css'];require VP3_ROOT.'/includes/header.php';?>
<section class="auth-layout"><div class="auth-visual reels-auth-visual"><div class="auth-visual-copy"><span class="eyebrow">Watch your way</span><h2>Follow the creators and stories you want to see next.</h2></div></div><div class="auth-panel"><div class="auth-panel-inner"><span class="eyebrow">Viewer account</span><h1>Build your feed.</h1><p class="auth-intro">Create a free viewer account for follows, saved clips, likes, history, and personalized recommendations.</p><?php if($error):?><div class="flash error"><?=vp3_e($error)?></div><?php endif;?><form method="post"><?=vp3_csrf_field()?><div class="field-row"><div class="field"><label>Display name<input name="display_name" required maxlength="150" value="<?=vp3_e((string)($_POST['display_name']??''))?>"></label></div><div class="field"><label>Handle<input name="handle" required maxlength="30" pattern="[a-z0-9_]{3,30}" value="<?=vp3_e((string)($_POST['handle']??''))?>"></label></div></div><div class="field"><label>Email<input type="email" name="email" required value="<?=vp3_e((string)($_POST['email']??''))?>"></label></div><div class="field"><label>Password<input type="password" name="password" minlength="12" required></label><span class="helper">Use at least 12 characters.</span></div><button class="button auth-submit">Create viewer account</button></form><p class="auth-switch">Already watching? <a href="viewer-login.php">Viewer sign in</a></p><p class="auth-note">Creator or license holder? <a href="login.php">Use the VP3 customer sign in.</a></p></div></div></section>
<?php require VP3_ROOT.'/includes/footer.php';?>
