SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE admins MODIFY COLUMN role ENUM('owner','super_admin','operations','sales','project_manager','creative_director','writer','producer','support','billing','hosting_operations') NOT NULL DEFAULT 'operations';

CREATE TABLE IF NOT EXISTS leads (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 lead_uuid CHAR(36) NOT NULL,
 customer_id BIGINT UNSIGNED NULL,
 assigned_admin_id BIGINT UNSIGNED NULL,
 source VARCHAR(80) NOT NULL DEFAULT 'website',
 source_detail VARCHAR(190) NULL,
 name VARCHAR(150) NOT NULL,
 email VARCHAR(190) NOT NULL,
 phone VARCHAR(40) NULL,
 company_name VARCHAR(190) NULL,
 project_name VARCHAR(190) NULL,
 project_type VARCHAR(80) NULL,
 budget_range VARCHAR(80) NULL,
 target_launch_date DATE NULL,
 summary TEXT NULL,
 stage ENUM('new','qualified','discovery','proposal','negotiation','won','lost','archived') NOT NULL DEFAULT 'new',
 priority ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
 next_follow_up_at DATETIME NULL,
 last_contact_at DATETIME NULL,
 converted_at DATETIME NULL,
 lost_reason VARCHAR(255) NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 UNIQUE KEY uq_leads_uuid (lead_uuid),
 KEY idx_leads_stage_followup (stage,next_follow_up_at),
 KEY idx_leads_email_created (email,created_at),
 KEY idx_leads_assigned_stage (assigned_admin_id,stage),
 CONSTRAINT fk_leads_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON UPDATE CASCADE ON DELETE SET NULL,
 CONSTRAINT fk_leads_admin FOREIGN KEY (assigned_admin_id) REFERENCES admins(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS demo_requests (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 request_uuid CHAR(36) NOT NULL,
 lead_id BIGINT UNSIGNED NOT NULL,
 preferred_date DATE NULL,
 preferred_time_window VARCHAR(80) NULL,
 timezone VARCHAR(80) NULL,
 meeting_format ENUM('video','phone','in_person','flexible') NOT NULL DEFAULT 'video',
 attendee_count SMALLINT UNSIGNED NOT NULL DEFAULT 1,
 goals TEXT NULL,
 status ENUM('requested','scheduled','completed','cancelled','no_show') NOT NULL DEFAULT 'requested',
 scheduled_at DATETIME NULL,
 meeting_url VARCHAR(500) NULL,
 internal_notes TEXT NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 UNIQUE KEY uq_demo_requests_uuid (request_uuid),
 KEY idx_demo_status_date (status,preferred_date),
 CONSTRAINT fk_demo_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lead_notes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 lead_id BIGINT UNSIGNED NOT NULL,
 admin_id BIGINT UNSIGNED NOT NULL,
 note TEXT NOT NULL,
 visibility ENUM('internal','customer_safe') NOT NULL DEFAULT 'internal',
 created_at DATETIME NOT NULL,
 KEY idx_lead_notes_lead_created (lead_id,created_at),
 CONSTRAINT fk_lead_notes_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT fk_lead_notes_admin FOREIGN KEY (admin_id) REFERENCES admins(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lead_activities (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 lead_id BIGINT UNSIGNED NOT NULL,
 admin_id BIGINT UNSIGNED NULL,
 activity_type ENUM('created','email','phone','meeting','note','stage_change','follow_up','proposal','conversion','system') NOT NULL,
 title VARCHAR(190) NOT NULL,
 details TEXT NULL,
 metadata_json JSON NULL,
 occurred_at DATETIME NOT NULL,
 created_at DATETIME NOT NULL,
 KEY idx_lead_activity_timeline (lead_id,occurred_at),
 CONSTRAINT fk_lead_activity_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT fk_lead_activity_admin FOREIGN KEY (admin_id) REFERENCES admins(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS service_packages (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 package_uuid CHAR(36) NOT NULL,
 package_key VARCHAR(100) NOT NULL,
 name VARCHAR(190) NOT NULL,
 slug VARCHAR(190) NOT NULL,
 short_description VARCHAR(500) NULL,
 description TEXT NULL,
 category ENUM('platform','creative','launch','management','custom') NOT NULL DEFAULT 'creative',
 billing_type ENUM('one_time','monthly','yearly','custom') NOT NULL DEFAULT 'one_time',
 price_cents INT UNSIGNED NOT NULL DEFAULT 0,
 setup_fee_cents INT UNSIGNED NOT NULL DEFAULT 0,
 currency CHAR(3) NOT NULL DEFAULT 'USD',
 delivery_days SMALLINT UNSIGNED NULL,
 featured_rank SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 status ENUM('draft','active','retired') NOT NULL DEFAULT 'draft',
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 UNIQUE KEY uq_service_packages_uuid (package_uuid),
 UNIQUE KEY uq_service_packages_key (package_key),
 UNIQUE KEY uq_service_packages_slug (slug),
 KEY idx_service_packages_public (status,featured_rank,category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS service_package_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 package_id BIGINT UNSIGNED NOT NULL,
 item_type ENUM('deliverable','feature','limit','support','timeline') NOT NULL DEFAULT 'deliverable',
 label VARCHAR(255) NOT NULL,
 description VARCHAR(500) NULL,
 quantity DECIMAL(10,2) NULL,
 unit VARCHAR(40) NULL,
 sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 created_at DATETIME NOT NULL,
 KEY idx_package_items_order (package_id,sort_order),
 CONSTRAINT fk_package_items_package FOREIGN KEY (package_id) REFERENCES service_packages(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS proposals (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 proposal_uuid CHAR(36) NOT NULL,
 proposal_number VARCHAR(50) NOT NULL,
 lead_id BIGINT UNSIGNED NULL,
 customer_id BIGINT UNSIGNED NULL,
 created_by_admin_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(190) NOT NULL,
 summary TEXT NULL,
 scope_text LONGTEXT NULL,
 terms_text LONGTEXT NULL,
 currency CHAR(3) NOT NULL DEFAULT 'USD',
 subtotal_cents INT UNSIGNED NOT NULL DEFAULT 0,
 discount_cents INT UNSIGNED NOT NULL DEFAULT 0,
 tax_cents INT UNSIGNED NOT NULL DEFAULT 0,
 total_cents INT UNSIGNED NOT NULL DEFAULT 0,
 deposit_cents INT UNSIGNED NOT NULL DEFAULT 0,
 status ENUM('draft','sent','viewed','accepted','declined','expired','cancelled') NOT NULL DEFAULT 'draft',
 valid_until DATE NULL,
 sent_at DATETIME NULL,
 viewed_at DATETIME NULL,
 accepted_at DATETIME NULL,
 declined_at DATETIME NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 UNIQUE KEY uq_proposals_uuid (proposal_uuid),
 UNIQUE KEY uq_proposals_number (proposal_number),
 KEY idx_proposals_customer_status (customer_id,status,created_at),
 KEY idx_proposals_lead_status (lead_id,status),
 CONSTRAINT fk_proposals_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON UPDATE CASCADE ON DELETE SET NULL,
 CONSTRAINT fk_proposals_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON UPDATE CASCADE ON DELETE SET NULL,
 CONSTRAINT fk_proposals_admin FOREIGN KEY (created_by_admin_id) REFERENCES admins(id) ON UPDATE CASCADE ON DELETE RESTRICT,
 CONSTRAINT chk_proposal_owner CHECK (lead_id IS NOT NULL OR customer_id IS NOT NULL),
 CONSTRAINT chk_proposal_total CHECK (total_cents = subtotal_cents - discount_cents + tax_cents)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS proposal_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 proposal_id BIGINT UNSIGNED NOT NULL,
 service_package_id BIGINT UNSIGNED NULL,
 item_type ENUM('package','service','license','hosting','deposit','discount','custom') NOT NULL DEFAULT 'service',
 name VARCHAR(190) NOT NULL,
 description TEXT NULL,
 quantity DECIMAL(10,2) NOT NULL DEFAULT 1.00,
 unit_price_cents INT NOT NULL DEFAULT 0,
 total_cents INT NOT NULL DEFAULT 0,
 billing_type ENUM('one_time','monthly','yearly','custom') NOT NULL DEFAULT 'one_time',
 sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 KEY idx_proposal_items_order (proposal_id,sort_order),
 CONSTRAINT fk_proposal_items_proposal FOREIGN KEY (proposal_id) REFERENCES proposals(id) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT fk_proposal_items_package FOREIGN KEY (service_package_id) REFERENCES service_packages(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS proposal_acceptances (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 proposal_id BIGINT UNSIGNED NOT NULL,
 customer_id BIGINT UNSIGNED NOT NULL,
 accepted_name VARCHAR(190) NOT NULL,
 accepted_email VARCHAR(190) NOT NULL,
 terms_version VARCHAR(50) NOT NULL,
 ip_address VARCHAR(45) NULL,
 user_agent_hash CHAR(64) NULL,
 acceptance_statement VARCHAR(500) NOT NULL,
 accepted_at DATETIME NOT NULL,
 UNIQUE KEY uq_proposal_acceptance (proposal_id),
 CONSTRAINT fk_acceptance_proposal FOREIGN KEY (proposal_id) REFERENCES proposals(id) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT fk_acceptance_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS project_briefs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 brief_uuid CHAR(36) NOT NULL,
 customer_id BIGINT UNSIGNED NOT NULL,
 lead_id BIGINT UNSIGNED NULL,
 project_name VARCHAR(190) NOT NULL,
 brand_name VARCHAR(190) NULL,
 concept_summary TEXT NOT NULL,
 audience_summary TEXT NULL,
 content_formats_json JSON NULL,
 existing_assets_summary TEXT NULL,
 launch_goals TEXT NULL,
 target_launch_date DATE NULL,
 hosting_preference ENUM('undecided','self_hosted','vp3_hosted','enterprise') NOT NULL DEFAULT 'undecided',
 creative_services_json JSON NULL,
 collaborators_summary TEXT NULL,
 references_summary TEXT NULL,
 status ENUM('draft','submitted','under_review','approved','revision_requested','archived') NOT NULL DEFAULT 'draft',
 submitted_at DATETIME NULL,
 reviewed_at DATETIME NULL,
 reviewed_by_admin_id BIGINT UNSIGNED NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 UNIQUE KEY uq_project_briefs_uuid (brief_uuid),
 KEY idx_project_briefs_customer_status (customer_id,status,updated_at),
 CONSTRAINT fk_project_briefs_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON UPDATE CASCADE ON DELETE RESTRICT,
 CONSTRAINT fk_project_briefs_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON UPDATE CASCADE ON DELETE SET NULL,
 CONSTRAINT fk_project_briefs_reviewer FOREIGN KEY (reviewed_by_admin_id) REFERENCES admins(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS creative_projects (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 project_uuid CHAR(36) NOT NULL,
 customer_id BIGINT UNSIGNED NOT NULL,
 brief_id BIGINT UNSIGNED NULL,
 proposal_id BIGINT UNSIGNED NULL,
 creator_id BIGINT UNSIGNED NULL,
 show_id BIGINT UNSIGNED NULL,
 project_manager_admin_id BIGINT UNSIGNED NULL,
 title VARCHAR(190) NOT NULL,
 slug VARCHAR(190) NOT NULL,
 project_type VARCHAR(80) NOT NULL DEFAULT 'media_platform',
 summary TEXT NULL,
 phase ENUM('discovery','strategy','development','production','launch','active','paused','completed','cancelled') NOT NULL DEFAULT 'discovery',
 health_status ENUM('on_track','at_risk','blocked','complete') NOT NULL DEFAULT 'on_track',
 readiness_percent TINYINT UNSIGNED NOT NULL DEFAULT 0,
 target_launch_date DATE NULL,
 actual_launch_date DATE NULL,
 status ENUM('draft','active','paused','completed','archived') NOT NULL DEFAULT 'draft',
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 UNIQUE KEY uq_creative_projects_uuid (project_uuid),
 UNIQUE KEY uq_creative_projects_customer_slug (customer_id,slug),
 KEY idx_projects_customer_status (customer_id,status,updated_at),
 KEY idx_projects_manager_phase (project_manager_admin_id,phase,health_status),
 CONSTRAINT fk_projects_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON UPDATE CASCADE ON DELETE RESTRICT,
 CONSTRAINT fk_projects_brief FOREIGN KEY (brief_id) REFERENCES project_briefs(id) ON UPDATE CASCADE ON DELETE SET NULL,
 CONSTRAINT fk_projects_proposal FOREIGN KEY (proposal_id) REFERENCES proposals(id) ON UPDATE CASCADE ON DELETE SET NULL,
 CONSTRAINT fk_projects_creator FOREIGN KEY (creator_id) REFERENCES creators(id) ON UPDATE CASCADE ON DELETE SET NULL,
 CONSTRAINT fk_projects_show FOREIGN KEY (show_id) REFERENCES shows(id) ON UPDATE CASCADE ON DELETE SET NULL,
 CONSTRAINT fk_projects_manager FOREIGN KEY (project_manager_admin_id) REFERENCES admins(id) ON UPDATE CASCADE ON DELETE SET NULL,
 CONSTRAINT chk_project_readiness CHECK (readiness_percent <= 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS project_members (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 project_id BIGINT UNSIGNED NOT NULL,
 member_type ENUM('admin','customer','external') NOT NULL,
 admin_id BIGINT UNSIGNED NULL,
 customer_id BIGINT UNSIGNED NULL,
 external_name VARCHAR(190) NULL,
 external_email VARCHAR(190) NULL,
 project_role VARCHAR(100) NOT NULL,
 permissions_json JSON NULL,
 status ENUM('invited','active','inactive','removed') NOT NULL DEFAULT 'active',
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 KEY idx_project_members_project_status (project_id,status),
 CONSTRAINT fk_project_members_project FOREIGN KEY (project_id) REFERENCES creative_projects(id) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT fk_project_members_admin FOREIGN KEY (admin_id) REFERENCES admins(id) ON UPDATE CASCADE ON DELETE SET NULL,
 CONSTRAINT fk_project_members_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON UPDATE CASCADE ON DELETE SET NULL,
 CONSTRAINT chk_project_member_identity CHECK (
   (member_type='admin' AND admin_id IS NOT NULL AND customer_id IS NULL)
   OR (member_type='customer' AND customer_id IS NOT NULL AND admin_id IS NULL)
   OR (member_type='external' AND external_email IS NOT NULL AND admin_id IS NULL AND customer_id IS NULL)
 )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS project_milestones (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 milestone_uuid CHAR(36) NOT NULL,
 project_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(190) NOT NULL,
 description TEXT NULL,
 phase VARCHAR(80) NULL,
 due_date DATE NULL,
 completed_at DATETIME NULL,
 status ENUM('planned','active','at_risk','blocked','completed','cancelled') NOT NULL DEFAULT 'planned',
 sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 UNIQUE KEY uq_project_milestones_uuid (milestone_uuid),
 KEY idx_milestones_project_order (project_id,status,sort_order,due_date),
 CONSTRAINT fk_milestones_project FOREIGN KEY (project_id) REFERENCES creative_projects(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS project_tasks (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 task_uuid CHAR(36) NOT NULL,
 project_id BIGINT UNSIGNED NOT NULL,
 milestone_id BIGINT UNSIGNED NULL,
 depends_on_task_id BIGINT UNSIGNED NULL,
 assigned_admin_id BIGINT UNSIGNED NULL,
 assigned_customer_id BIGINT UNSIGNED NULL,
 created_by_type ENUM('admin','customer','system','ai') NOT NULL DEFAULT 'admin',
 created_by_id BIGINT UNSIGNED NULL,
 title VARCHAR(190) NOT NULL,
 description TEXT NULL,
 task_type VARCHAR(80) NOT NULL DEFAULT 'general',
 priority ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
 status ENUM('backlog','ready','in_progress','waiting','review','completed','cancelled') NOT NULL DEFAULT 'backlog',
 due_at DATETIME NULL,
 started_at DATETIME NULL,
 completed_at DATETIME NULL,
 estimated_minutes INT UNSIGNED NULL,
 sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 metadata_json JSON NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 UNIQUE KEY uq_project_tasks_uuid (task_uuid),
 KEY idx_tasks_project_status_due (project_id,status,due_at),
 KEY idx_tasks_admin_queue (assigned_admin_id,status,due_at),
 KEY idx_tasks_customer_queue (assigned_customer_id,status,due_at),
 CONSTRAINT fk_tasks_project FOREIGN KEY (project_id) REFERENCES creative_projects(id) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT fk_tasks_milestone FOREIGN KEY (milestone_id) REFERENCES project_milestones(id) ON UPDATE CASCADE ON DELETE SET NULL,
 CONSTRAINT fk_tasks_dependency FOREIGN KEY (depends_on_task_id) REFERENCES project_tasks(id) ON UPDATE CASCADE ON DELETE SET NULL,
 CONSTRAINT fk_tasks_admin FOREIGN KEY (assigned_admin_id) REFERENCES admins(id) ON UPDATE CASCADE ON DELETE SET NULL,
 CONSTRAINT fk_tasks_customer FOREIGN KEY (assigned_customer_id) REFERENCES customers(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS project_assets (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 asset_uuid CHAR(36) NOT NULL,
 project_id BIGINT UNSIGNED NOT NULL,
 uploaded_by_type ENUM('admin','customer','system') NOT NULL,
 uploaded_by_id BIGINT UNSIGNED NULL,
 category VARCHAR(80) NOT NULL DEFAULT 'general',
 title VARCHAR(190) NOT NULL,
 description TEXT NULL,
 original_name VARCHAR(255) NULL,
 mime_type VARCHAR(120) NULL,
 size_bytes BIGINT UNSIGNED NULL,
 storage_provider VARCHAR(80) NOT NULL DEFAULT 'external_reference',
 storage_key VARCHAR(500) NULL,
 external_url VARCHAR(1000) NULL,
 sha256 CHAR(64) NULL,
 version_number INT UNSIGNED NOT NULL DEFAULT 1,
 parent_asset_id BIGINT UNSIGNED NULL,
 visibility ENUM('internal','customer','shared') NOT NULL DEFAULT 'shared',
 approval_status ENUM('not_required','pending','approved','revision_requested','rejected') NOT NULL DEFAULT 'not_required',
 status ENUM('active','archived','deleted') NOT NULL DEFAULT 'active',
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 UNIQUE KEY uq_project_assets_uuid (asset_uuid),
 KEY idx_assets_project_category (project_id,status,category,updated_at),
 KEY idx_assets_parent_version (parent_asset_id,version_number),
 CONSTRAINT fk_assets_project FOREIGN KEY (project_id) REFERENCES creative_projects(id) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT fk_assets_parent FOREIGN KEY (parent_asset_id) REFERENCES project_assets(id) ON UPDATE CASCADE ON DELETE SET NULL,
 CONSTRAINT chk_asset_reference CHECK (storage_key IS NOT NULL OR external_url IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS project_approvals (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 approval_uuid CHAR(36) NOT NULL,
 project_id BIGINT UNSIGNED NOT NULL,
 task_id BIGINT UNSIGNED NULL,
 asset_id BIGINT UNSIGNED NULL,
 requested_by_admin_id BIGINT UNSIGNED NOT NULL,
 requested_from_customer_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(190) NOT NULL,
 instructions TEXT NULL,
 status ENUM('pending','approved','revision_requested','rejected','cancelled','expired') NOT NULL DEFAULT 'pending',
 response_notes TEXT NULL,
 due_at DATETIME NULL,
 requested_at DATETIME NOT NULL,
 responded_at DATETIME NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 UNIQUE KEY uq_project_approvals_uuid (approval_uuid),
 KEY idx_approvals_customer_status (requested_from_customer_id,status,due_at),
 KEY idx_approvals_project_status (project_id,status,created_at),
 CONSTRAINT fk_approvals_project FOREIGN KEY (project_id) REFERENCES creative_projects(id) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT fk_approvals_task FOREIGN KEY (task_id) REFERENCES project_tasks(id) ON UPDATE CASCADE ON DELETE SET NULL,
 CONSTRAINT fk_approvals_asset FOREIGN KEY (asset_id) REFERENCES project_assets(id) ON UPDATE CASCADE ON DELETE SET NULL,
 CONSTRAINT fk_approvals_admin FOREIGN KEY (requested_by_admin_id) REFERENCES admins(id) ON UPDATE CASCADE ON DELETE RESTRICT,
 CONSTRAINT fk_approvals_customer FOREIGN KEY (requested_from_customer_id) REFERENCES customers(id) ON UPDATE CASCADE ON DELETE RESTRICT,
 CONSTRAINT chk_approval_subject CHECK (task_id IS NOT NULL OR asset_id IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS project_comments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 project_id BIGINT UNSIGNED NOT NULL,
 task_id BIGINT UNSIGNED NULL,
 asset_id BIGINT UNSIGNED NULL,
 author_type ENUM('admin','customer','system','ai') NOT NULL,
 author_id BIGINT UNSIGNED NULL,
 visibility ENUM('internal','customer','shared') NOT NULL DEFAULT 'shared',
 comment TEXT NOT NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 KEY idx_project_comments_timeline (project_id,visibility,created_at),
 KEY idx_project_comments_task (task_id,created_at),
 CONSTRAINT fk_comments_project FOREIGN KEY (project_id) REFERENCES creative_projects(id) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT fk_comments_task FOREIGN KEY (task_id) REFERENCES project_tasks(id) ON UPDATE CASCADE ON DELETE SET NULL,
 CONSTRAINT fk_comments_asset FOREIGN KEY (asset_id) REFERENCES project_assets(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS production_plans (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 plan_uuid CHAR(36) NOT NULL,
 project_id BIGINT UNSIGNED NOT NULL,
 generated_by ENUM('admin','customer','system','ai') NOT NULL DEFAULT 'admin',
 generated_by_id BIGINT UNSIGNED NULL,
 title VARCHAR(190) NOT NULL,
 objective TEXT NULL,
 assumptions_json JSON NULL,
 status ENUM('draft','review','approved','active','completed','archived') NOT NULL DEFAULT 'draft',
 version_number INT UNSIGNED NOT NULL DEFAULT 1,
 approved_by_customer_id BIGINT UNSIGNED NULL,
 approved_at DATETIME NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 UNIQUE KEY uq_production_plans_uuid (plan_uuid),
 KEY idx_production_plans_project (project_id,status,version_number),
 CONSTRAINT fk_production_plans_project FOREIGN KEY (project_id) REFERENCES creative_projects(id) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT fk_production_plans_customer FOREIGN KEY (approved_by_customer_id) REFERENCES customers(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS production_plan_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 plan_id BIGINT UNSIGNED NOT NULL,
 milestone_id BIGINT UNSIGNED NULL,
 title VARCHAR(190) NOT NULL,
 description TEXT NULL,
 item_type ENUM('milestone','task_group','content','asset','review','launch_gate','risk') NOT NULL DEFAULT 'task_group',
 target_date DATE NULL,
 owner_type ENUM('vp3','customer','shared','external') NOT NULL DEFAULT 'shared',
 status ENUM('planned','active','completed','blocked','removed') NOT NULL DEFAULT 'planned',
 sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 KEY idx_plan_items_order (plan_id,status,sort_order,target_date),
 CONSTRAINT fk_plan_items_plan FOREIGN KEY (plan_id) REFERENCES production_plans(id) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT fk_plan_items_milestone FOREIGN KEY (milestone_id) REFERENCES project_milestones(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS project_activity (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 project_id BIGINT UNSIGNED NOT NULL,
 actor_type ENUM('admin','customer','system','ai') NOT NULL,
 actor_id BIGINT UNSIGNED NULL,
 action VARCHAR(100) NOT NULL,
 entity_type VARCHAR(80) NULL,
 entity_uuid CHAR(36) NULL,
 summary VARCHAR(500) NOT NULL,
 metadata_json JSON NULL,
 created_at DATETIME NOT NULL,
 KEY idx_project_activity_timeline (project_id,created_at),
 CONSTRAINT fk_project_activity_project FOREIGN KEY (project_id) REFERENCES creative_projects(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notifications (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 notification_uuid CHAR(36) NOT NULL,
 recipient_type ENUM('admin','customer') NOT NULL,
 recipient_id BIGINT UNSIGNED NOT NULL,
 category VARCHAR(80) NOT NULL,
 title VARCHAR(190) NOT NULL,
 message VARCHAR(1000) NOT NULL,
 action_url VARCHAR(500) NULL,
 entity_type VARCHAR(80) NULL,
 entity_uuid CHAR(36) NULL,
 status ENUM('unread','read','archived') NOT NULL DEFAULT 'unread',
 read_at DATETIME NULL,
 created_at DATETIME NOT NULL,
 UNIQUE KEY uq_notifications_uuid (notification_uuid),
 KEY idx_notifications_recipient (recipient_type,recipient_id,status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS=1;
