<?php
declare(strict_types=1);
require dirname(__DIR__) . '/bootstrap.php';
$admin=vp3_require_admin_permission('clips.moderate');
$id=(int)vp3_input('id');
$stmt=vp3_db()->prepare("SELECT cp.*,ppl.display_name platform_name,ppl.public_domain,c.display_name creator_name,s.title show_title FROM clip_publications cp JOIN public_platform_listings ppl ON ppl.id=cp.public_listing_id LEFT JOIN creators c ON c.id=cp.creator_id LEFT JOIN shows s ON s.id=cp.show_id WHERE cp.id=? LIMIT 1");
$stmt->execute([$id]);$row=$stmt->fetch();if(!$row){http_response_code(404);exit('Clip not found.');}
if(vp3_method()==='POST'){
    vp3_verify_csrf();
    $moderation=vp3_input('moderation_status');$rights=vp3_input('rights_status');$publication=vp3_input('publication_status');
    if(!in_array($moderation,['pending','approved','rejected','flagged'],true)||!in_array($rights,['pending','confirmed','disputed','expired'],true)||!in_array($publication,['pending','scheduled','published','withdrawn','suspended'],true)){throw new RuntimeException('invalid_clip_status');}
    $feed=vp3_input('feed_eligible')==='1'?1:0;$featured=max(0,(int)vp3_input('featured_rank'));
    if($publication==='published'&&($moderation!=='approved'||$rights!=='confirmed')){vp3_flash('error','A clip must be approved and rights-confirmed before publication.');vp3_redirect('admin/clip.php?id='.$id);}
    $publishedAt=$publication==='published'?($row['published_at']?:date('Y-m-d H:i:s')):null;
    vp3_db()->prepare('UPDATE clip_publications SET moderation_status=?,rights_status=?,publication_status=?,feed_eligible=?,featured_rank=?,published_at=?,updated_at=NOW() WHERE id=?')->execute([$moderation,$rights,$publication,$feed,$featured,$publishedAt,$id]);
    $notes=trim(vp3_input('review_notes'));
    if($notes!==''||$moderation!==$row['moderation_status']){vp3_db()->prepare('INSERT INTO clip_moderation_reviews (clip_publication_id,admin_id,decision,review_notes,created_at) VALUES (?,?,?,?,NOW())')->execute([$id,(int)$admin['id'],$moderation,$notes?:null]);}
    if(vp3_input('resolve_reports')==='1'){vp3_db()->prepare("UPDATE clip_reports SET report_status='resolved',resolved_by=?,resolved_at=NOW(),updated_at=NOW() WHERE clip_publication_id=? AND report_status='open'")->execute([(int)$admin['id'],$id]);}
    vp3_audit('admin',(int)$admin['id'],'clip.moderated','clip_publication',(string)$row['publication_uuid'],['moderation'=>$moderation,'rights'=>$rights,'publication'=>$publication]);
    vp3_flash('success','Clip review saved.');vp3_redirect('admin/clip.php?id='.$id);
}
$reviews=vp3_db()->prepare('SELECT cmr.*,a.name admin_name FROM clip_moderation_reviews cmr JOIN admins a ON a.id=cmr.admin_id WHERE cmr.clip_publication_id=? ORDER BY cmr.id DESC');$reviews->execute([$id]);$reviews=$reviews->fetchAll();
$reports=vp3_db()->prepare('SELECT * FROM clip_reports WHERE clip_publication_id=? ORDER BY id DESC');$reports->execute([$id]);$reports=$reports->fetchAll();
$pageTitle='Review Clip';require VP3_ROOT.'/includes/admin-header.php';
?>
<div class="admin-page-head"><div><span class="admin-kicker">VP3 Clips</span><h1><?=vp3_e($row['title'])?></h1><p><?=vp3_e($row['platform_name'])?> · <?=vp3_e($row['public_domain'])?></p></div><a class="button secondary" href="clips.php">Back to queue</a></div>
<div class="admin-split"><section class="card"><h2>Source publication</h2><dl class="detail-list"><dt>Creator</dt><dd><?=vp3_e($row['creator_name']??'Unassigned')?></dd><dt>Show</dt><dd><?=vp3_e($row['show_title']??'Unassigned')?></dd><dt>Caption</dt><dd><?=nl2br(vp3_e($row['caption']))?></dd><dt>Duration</dt><dd><?=(int)$row['duration_seconds']?> seconds · <?=vp3_e($row['aspect_ratio'])?></dd><dt>Media URL</dt><dd><a href="<?=vp3_e($row['source_media_url'])?>" rel="noreferrer" target="_blank">Open source media</a></dd><dt>Destination</dt><dd><a href="<?=vp3_e($row['destination_url'])?>" rel="noreferrer" target="_blank">Open creator destination</a></dd><dt>Source updated</dt><dd><?=vp3_e($row['source_updated_at'])?></dd></dl></section>
<form class="card admin-form" method="post"><?=vp3_csrf_field()?><h2>Moderation controls</h2><div class="field"><label>Moderation</label><select name="moderation_status"><?php foreach(['pending','approved','rejected','flagged'] as $v):?><option <?= $row['moderation_status']===$v?'selected':'' ?>><?=$v?></option><?php endforeach;?></select></div><div class="field"><label>Rights</label><select name="rights_status"><?php foreach(['pending','confirmed','disputed','expired'] as $v):?><option <?= $row['rights_status']===$v?'selected':'' ?>><?=$v?></option><?php endforeach;?></select></div><div class="field"><label>Publication</label><select name="publication_status"><?php foreach(['pending','scheduled','published','withdrawn','suspended'] as $v):?><option <?= $row['publication_status']===$v?'selected':'' ?>><?=$v?></option><?php endforeach;?></select></div><div class="field"><label>Featured rank</label><input name="featured_rank" type="number" min="0" value="<?=(int)$row['featured_rank']?>"></div><label class="check-row"><input type="checkbox" name="feed_eligible" value="1" <?=$row['feed_eligible']?'checked':''?>> Eligible for VP3 Clips feeds</label><div class="field"><label>Review notes</label><textarea name="review_notes"></textarea></div><?php if($reports):?><label class="check-row"><input type="checkbox" name="resolve_reports" value="1"> Resolve all open reports</label><?php endif;?><button class="button">Save review</button></form></div>
<?php if($reports):?><section class="card admin-section"><h2>Reports</h2><div class="table-wrap"><table class="table"><thead><tr><th>Reason</th><th>Details</th><th>Status</th><th>Created</th></tr></thead><tbody><?php foreach($reports as $report):?><tr><td><?=vp3_e($report['reason'])?></td><td><?=vp3_e($report['details'])?></td><td><?=vp3_e($report['report_status'])?></td><td><?=vp3_e($report['created_at'])?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
<section class="card admin-section"><h2>Review history</h2><?php if(!$reviews):?><p class="helper">No prior moderation reviews.</p><?php else:?><div class="activity-list"><?php foreach($reviews as $review):?><article><b><?=vp3_e($review['decision'])?></b><span><?=vp3_e($review['admin_name'])?> · <?=vp3_e($review['created_at'])?></span><p><?=vp3_e($review['review_notes'])?></p></article><?php endforeach;?></div><?php endif;?></section>
<?php require VP3_ROOT.'/includes/admin-footer.php';?>
