<?php
declare(strict_types=1);
require dirname(__DIR__) . '/bootstrap.php';
$admin = vp3_require_admin_permission('network.manage');
$id = (int)vp3_input('id');
if (vp3_method()==='POST') {
    vp3_verify_csrf();
    $customerId=(int)vp3_input('customer_id'); $name=vp3_input('display_name'); $slug=preg_replace('/[^a-z0-9-]/','',strtolower(vp3_input('slug')))?:'';
    if ($customerId<1 || $name==='' || $slug==='') { vp3_flash('error','Customer, display name, and slug are required.'); vp3_redirect('admin/creator.php'.($id?'?id='.$id:'')); }
    $data=[$customerId,$name,$slug,vp3_input('headline'),vp3_input('bio'),vp3_input('avatar_url'),vp3_input('cover_url'),vp3_input('website_url'),vp3_input('verification_status'),vp3_input('listing_status'),max(0,(int)vp3_input('featured_rank')),vp3_input('clips_syndication_default')];
    if ($id>0) { $stmt=vp3_db()->prepare('UPDATE creators SET customer_id=?,display_name=?,slug=?,headline=?,bio=?,avatar_url=NULLIF(?,\'\'),cover_url=NULLIF(?,\'\'),website_url=NULLIF(?,\'\'),verification_status=?,listing_status=?,featured_rank=?,clips_syndication_default=?,updated_at=NOW() WHERE id=?'); $stmt->execute([...$data,$id]); $uuid=(string)vp3_db()->query('SELECT creator_uuid FROM creators WHERE id='.(int)$id)->fetchColumn(); }
    else { $uuid=vp3_uuid(); $stmt=vp3_db()->prepare('INSERT INTO creators (creator_uuid,customer_id,display_name,slug,headline,bio,avatar_url,cover_url,website_url,verification_status,listing_status,featured_rank,clips_syndication_default,created_at,updated_at) VALUES (?,?,?,?,?,?,NULLIF(?,\'\'),NULLIF(?,\'\'),NULLIF(?,\'\'),?,?,?,?,NOW(),NOW())'); $stmt->execute([$uuid,...$data]); $id=(int)vp3_db()->lastInsertId(); }
    vp3_audit('admin',(int)$admin['id'],'creator.saved','creator',$uuid,['id'=>$id]); vp3_flash('success','Creator saved.'); vp3_redirect('admin/creator.php?id='.$id);
}
$row=null;if($id>0){$s=vp3_db()->prepare('SELECT * FROM creators WHERE id=?');$s->execute([$id]);$row=$s->fetch();if(!$row){http_response_code(404);exit('Creator not found.');}}
$customers=vp3_db()->query("SELECT id,name,email FROM customers WHERE status IN ('active','pending') ORDER BY name")->fetchAll();
$pageTitle=$row?'Edit Creator':'Add Creator';require VP3_ROOT.'/includes/admin-header.php';
?>
<div class="admin-page-head"><div><span class="admin-kicker">VP3 Network</span><h1><?=vp3_e($pageTitle)?></h1></div><a class="button secondary" href="creators.php">Back to creators</a></div>
<form class="card admin-form" method="post"><?=vp3_csrf_field()?><div class="admin-form-grid"><div class="field"><label>Customer</label><select name="customer_id" required><option value="">Select</option><?php foreach($customers as $customer):?><option value="<?=(int)$customer['id']?>" <?= (int)($row['customer_id']??0)===(int)$customer['id']?'selected':'' ?>><?=vp3_e($customer['name'].' · '.$customer['email'])?></option><?php endforeach;?></select></div><div class="field"><label>Display name</label><input name="display_name" value="<?=vp3_e($row['display_name']??'')?>" required></div><div class="field"><label>Slug</label><input name="slug" value="<?=vp3_e($row['slug']??'')?>" pattern="[a-z0-9-]+" required></div><div class="field"><label>Headline</label><input name="headline" value="<?=vp3_e($row['headline']??'')?>"></div><div class="field full"><label>Biography</label><textarea name="bio"><?=vp3_e($row['bio']??'')?></textarea></div><div class="field"><label>Avatar URL (HTTPS)</label><input name="avatar_url" type="url" value="<?=vp3_e($row['avatar_url']??'')?>"></div><div class="field"><label>Cover URL (HTTPS)</label><input name="cover_url" type="url" value="<?=vp3_e($row['cover_url']??'')?>"></div><div class="field"><label>Official website</label><input name="website_url" type="url" value="<?=vp3_e($row['website_url']??'')?>"></div><div class="field"><label>Verification</label><select name="verification_status"><?php foreach(['pending','verified','rejected','suspended'] as $value):?><option <?=($row['verification_status']??'pending')===$value?'selected':''?>><?=$value?></option><?php endforeach;?></select></div><div class="field"><label>Public listing</label><select name="listing_status"><?php foreach(['draft','published','hidden','archived'] as $value):?><option <?=($row['listing_status']??'draft')===$value?'selected':''?>><?=$value?></option><?php endforeach;?></select></div><div class="field"><label>Featured rank</label><input name="featured_rank" type="number" min="0" value="<?=vp3_e($row['featured_rank']??0)?>"></div><div class="field"><label>Default clip syndication</label><select name="clips_syndication_default"><?php foreach(['off','manual','public'] as $value):?><option <?=($row['clips_syndication_default']??'manual')===$value?'selected':''?>><?=$value?></option><?php endforeach;?></select></div></div><button class="button">Save creator</button></form>
<?php require VP3_ROOT.'/includes/admin-footer.php'; ?>
