<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
use VP3\Network\BridgeCredentialService;
$admin=vp3_require_admin_permission('network.manage');$listingId=(int)vp3_input('id');
$stmt=vp3_db()->prepare('SELECT ppl.*,c.name customer_name,p.name product_name,l.edition FROM public_platform_listings ppl JOIN customers c ON c.id=ppl.customer_id JOIN products p ON p.id=ppl.product_id JOIN licenses l ON l.id=ppl.license_id WHERE ppl.id=?');$stmt->execute([$listingId]);$listing=$stmt->fetch();if(!$listing){http_response_code(404);exit('Platform not found.');}
if(vp3_method()==='POST'){
    vp3_verify_csrf();$action=vp3_input('action');$service=new BridgeCredentialService(vp3_db());
    if($action==='issue'){$issued=$service->issue($listingId,(int)vp3_input('activation_id'),(int)$admin['id'],vp3_input('expires_at')?:null);$_SESSION['vp3_bridge_secret_once']=$issued;vp3_flash('success','A new bridge credential was issued in certification mode. Copy the secret now; it will not be shown again.');}
    elseif($action==='revoke'){$service->revoke((int)vp3_input('credential_id'),$listingId,(int)$admin['id']);vp3_flash('success','Bridge credential revoked.');}
    vp3_redirect('admin/platform-bridge.php?id='.$listingId);
}
$activations=vp3_db()->prepare("SELECT id,installation_uuid,domain,status,last_validated_at FROM license_activations WHERE license_id=? ORDER BY status='active' DESC,id DESC");$activations->execute([(int)$listing['license_id']]);$activations=$activations->fetchAll();
$credentials=vp3_db()->prepare("SELECT pbc.*,la.installation_uuid,la.domain,(SELECT status FROM platform_bridge_certifications cert WHERE cert.bridge_credential_id=pbc.id ORDER BY cert.id DESC LIMIT 1) certification_status,(SELECT expires_at FROM platform_bridge_certifications cert WHERE cert.bridge_credential_id=pbc.id AND cert.status='approved' ORDER BY cert.id DESC LIMIT 1) certification_expires_at FROM platform_bridge_credentials pbc JOIN license_activations la ON la.id=pbc.license_activation_id WHERE pbc.public_listing_id=? ORDER BY pbc.id DESC");$credentials->execute([$listingId]);$credentials=$credentials->fetchAll();
$secret=$_SESSION['vp3_bridge_secret_once']??null;unset($_SESSION['vp3_bridge_secret_once']);$pageTitle='Platform Clip Bridge';require VP3_ROOT.'/includes/admin-header.php';
?>
<div class="admin-page-head"><div><span class="admin-kicker">VP3 Clips source bridge</span><h1><?=vp3_e($listing['display_name'])?></h1><p>Issue a scoped credential to one licensed installation. New credentials begin in certification mode and cannot create or update feed publications until VP3 approves a passing environment report.</p></div><div><a class="button" href="platform-bridge-certification.php?id=<?=$listingId?>">Certification</a> <a class="button secondary" href="public-listing.php?id=<?=$listingId?>">Back to platform</a></div></div>
<?php if(is_array($secret)):?><section class="card bridge-secret-once"><span class="admin-kicker">Shown once</span><h2>Stonefellow bridge configuration</h2><p>Store this credential in Stonefellow's private bridge settings. VP3 stores the secret encrypted and never displays it again.</p><div class="table-wrap"><table class="table"><tbody><?php foreach(['bridge_uuid','bridge_secret','listing_uuid','installation_uuid','product_id','domain','source_creator_uuid','source_show_uuid'] as $key):?><tr><th><?=vp3_e($key)?></th><td><code><?=vp3_e((string)($secret[$key]??''))?></code></td></tr><?php endforeach;?></tbody></table></div><p><strong>Publishing mode:</strong> Certification. Stonefellow must submit a passing report, then a VP3 administrator must approve live publishing.</p></section><?php endif;?>
<section class="card admin-form"><h2>Issue or rotate credential</h2><form method="post"><?=vp3_csrf_field()?><input type="hidden" name="action" value="issue"><div class="admin-form-grid"><div class="field full"><label>Licensed installation</label><select name="activation_id" required><option value="">Select active installation</option><?php foreach($activations as $a):?><option value="<?=(int)$a['id']?>" <?=$a['status']!=='active'?'disabled':''?>><?=vp3_e($a['domain'].' · '.$a['installation_uuid'].' · '.$a['status'])?></option><?php endforeach;?></select></div><div class="field"><label>Optional expiration</label><input type="datetime-local" name="expires_at"></div></div><button class="button">Issue new credential</button></form></section>
<section class="card"><h2>Credential history</h2><div class="table-wrap"><table class="table"><thead><tr><th>Bridge ID</th><th>Installation</th><th>Status</th><th>Certification</th><th>Last used</th><th>Issued</th><th></th></tr></thead><tbody><?php foreach($credentials as $c):?><tr><td><code><?=vp3_e($c['bridge_uuid'])?></code></td><td><?=vp3_e($c['domain'])?><br><small><?=vp3_e($c['installation_uuid'])?></small></td><td><span class="badge <?=vp3_e($c['status'])?>"><?=vp3_e($c['status'])?></span></td><td><?=vp3_e((string)($c['certification_status']?:'not_started'))?><?php if($c['certification_expires_at']):?><br><small>through <?=vp3_e($c['certification_expires_at'])?></small><?php endif;?></td><td><?=vp3_e((string)$c['last_used_at'])?></td><td><?=vp3_e($c['created_at'])?></td><td><?php if($c['status']==='active'):?><form method="post"><?=vp3_csrf_field()?><input type="hidden" name="action" value="revoke"><input type="hidden" name="credential_id" value="<?=(int)$c['id']?>"><button class="button small secondary" type="submit">Revoke</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php require VP3_ROOT.'/includes/admin-footer.php';?>
