<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
use VP3\Projects\ProjectService;
$admin=vp3_require_admin_permission('projects.manage');$id=(int)vp3_input('id');$briefId=(int)vp3_input('brief_id');$service=new ProjectService(vp3_db());$row=null;$prefill=[];
if(!$id&&$briefId>0){$stmt=vp3_db()->prepare('SELECT pb.*,c.name customer_name,c.email customer_email FROM project_briefs pb JOIN customers c ON c.id=pb.customer_id WHERE pb.id=?');$stmt->execute([$briefId]);$brief=$stmt->fetch();if(is_array($brief))$prefill=['customer_id'=>$brief['customer_id'],'brief_id'=>$brief['id'],'title'=>$brief['project_name'],'summary'=>$brief['concept_summary'],'target_launch_date'=>$brief['target_launch_date']];}
if($id){$stmt=vp3_db()->prepare('SELECT p.*,c.name customer_name,c.email customer_email FROM creative_projects p JOIN customers c ON c.id=p.customer_id WHERE p.id=?');$stmt->execute([$id]);$row=$stmt->fetch();if(!$row){http_response_code(404);exit('Project not found.');}}
if(vp3_method()==='POST'){
    vp3_verify_csrf();$action=vp3_input('action','save');
    try{
        if($action==='save'){
            if($id){
                $creatorId=(int)vp3_input('creator_id');$showId=(int)vp3_input('show_id');$managerId=(int)vp3_input('project_manager_admin_id');
                if($managerId>0){$check=vp3_db()->prepare("SELECT COUNT(*) FROM admins WHERE id=? AND status='active'");$check->execute([$managerId]);if((int)$check->fetchColumn()<1)throw new RuntimeException('project_manager_not_available');}
                if($creatorId>0){$check=vp3_db()->prepare('SELECT COUNT(*) FROM creators WHERE id=? AND customer_id=?');$check->execute([$creatorId,$row['customer_id']]);if((int)$check->fetchColumn()<1)throw new RuntimeException('creator_customer_mismatch');}
                if($showId>0){$check=vp3_db()->prepare('SELECT COUNT(*) FROM shows WHERE id=? AND customer_id=?');$check->execute([$showId,$row['customer_id']]);if((int)$check->fetchColumn()<1)throw new RuntimeException('show_customer_mismatch');}
                $status=in_array(vp3_input('status'),['draft','active','paused','completed','archived'],true)?vp3_input('status'):'active';
                $phase=in_array(vp3_input('phase'),['discovery','strategy','development','production','launch','active','paused','completed','cancelled'],true)?vp3_input('phase'):'discovery';
                $health=in_array(vp3_input('health_status'),['on_track','at_risk','blocked','complete'],true)?vp3_input('health_status'):'on_track';
                vp3_db()->prepare("UPDATE creative_projects SET project_manager_admin_id=NULLIF(?,0),creator_id=NULLIF(?,0),show_id=NULLIF(?,0),title=?,project_type=?,summary=?,phase=?,health_status=?,target_launch_date=NULLIF(?,''),actual_launch_date=NULLIF(?,''),status=?,updated_at=NOW() WHERE id=?")
                    ->execute([$managerId,$creatorId,$showId,vp3_input('title'),vp3_input('project_type','media_platform'),vp3_input('summary'),$phase,$health,vp3_input('target_launch_date'),vp3_input('actual_launch_date'),$status,$id]);
                $service->recalculateReadiness($id);$service->activity($id,'admin',(int)$admin['id'],'project.updated','project',$row['project_uuid'],'Project details updated.');
            }else{
                $created=$service->create($_POST,(int)$admin['id']);$id=(int)$created['id'];
            }
        }elseif($action==='milestone'){$service->addMilestone($id,$_POST,(int)$admin['id']);}
        elseif($action==='task'){$service->addTask($id,$_POST,(int)$admin['id']);}
        elseif($action==='approval'){$service->requestApproval($id,$_POST,(int)$admin['id']);}
        elseif($action==='task_update'){
            $taskId=(int)vp3_input('task_id');$status=vp3_input('status');if(!in_array($status,['backlog','ready','in_progress','waiting','review','completed','cancelled'],true))throw new RuntimeException('invalid_task_status');
            $stmt=vp3_db()->prepare("UPDATE project_tasks SET status=?,started_at=CASE WHEN ?='in_progress' THEN COALESCE(started_at,NOW()) ELSE started_at END,completed_at=CASE WHEN ?='completed' THEN NOW() ELSE CASE WHEN ?<>'completed' THEN NULL ELSE completed_at END END,updated_at=NOW() WHERE id=? AND project_id=?");
            $stmt->execute([$status,$status,$status,$status,$taskId,$id]);if($stmt->rowCount()!==1)throw new RuntimeException('task_not_found');$service->recalculateReadiness($id);
        }
        elseif($action==='milestone_update'){
            $milestoneId=(int)vp3_input('milestone_id');$status=vp3_input('status');if(!in_array($status,['planned','active','at_risk','blocked','completed','cancelled'],true))throw new RuntimeException('invalid_milestone_status');
            $stmt=vp3_db()->prepare("UPDATE project_milestones SET status=?,completed_at=CASE WHEN ?='completed' THEN NOW() ELSE NULL END,updated_at=NOW() WHERE id=? AND project_id=?");
            $stmt->execute([$status,$status,$milestoneId,$id]);if($stmt->rowCount()!==1)throw new RuntimeException('milestone_not_found');
        }
        elseif($action==='comment'){
            $comment=vp3_input('comment');if(vp3_text_length($comment)<2)throw new RuntimeException('comment_required');
            vp3_db()->prepare("INSERT INTO project_comments(project_id,author_type,author_id,visibility,comment,created_at,updated_at) VALUES (?,'admin',?,?,?,NOW(),NOW())")->execute([$id,$admin['id'],vp3_input('visibility','shared'),$comment]);
            $service->activity($id,'admin',(int)$admin['id'],'comment.created','project',$row['project_uuid'],'VP3 added a project comment.');
        }elseif($action==='asset'){
            $title=vp3_input('asset_title');$url=vp3_public_https_url(vp3_input('external_url'));if($title===''||$url==='')throw new RuntimeException('asset_title_and_https_url_required');$uuid=vp3_uuid();
            vp3_db()->prepare("INSERT INTO project_assets(asset_uuid,project_id,uploaded_by_type,uploaded_by_id,category,title,description,external_url,visibility,approval_status,status,created_at,updated_at) VALUES (? ,?,'admin',?,?,?,?,?,?,?,'active',NOW(),NOW())")
                ->execute([$uuid,$id,$admin['id'],vp3_input('category','general'),$title,vp3_input('asset_description'),$url,vp3_input('visibility','shared'),vp3_input('approval_status','not_required')]);
            $service->activity($id,'admin',(int)$admin['id'],'asset.registered','asset',$uuid,'VP3 registered asset: '.$title);
        }elseif($action==='production_plan'){
            $title=vp3_input('plan_title');if($title==='')throw new RuntimeException('plan_title_required');$uuid=vp3_uuid();
            vp3_db()->prepare("INSERT INTO production_plans(plan_uuid,project_id,generated_by,generated_by_id,title,objective,status,version_number,created_at,updated_at) VALUES (?,?,'admin',?,?,?,'draft',1,NOW(),NOW())")->execute([$uuid,$id,$admin['id'],$title,vp3_input('objective')]);
            $service->activity($id,'admin',(int)$admin['id'],'production_plan.created','production_plan',$uuid,'Production plan foundation created.');
        }elseif($action==='plan_item'){
            $planId=(int)vp3_input('plan_id');$milestoneId=(int)vp3_input('milestone_id');$title=vp3_input('item_title');if($planId<1||$title==='')throw new RuntimeException('plan_and_item_required');
            $planCheck=vp3_db()->prepare('SELECT COUNT(*) FROM production_plans WHERE id=? AND project_id=?');$planCheck->execute([$planId,$id]);if((int)$planCheck->fetchColumn()<1)throw new RuntimeException('production_plan_not_found');
            if($milestoneId>0){$milestoneCheck=vp3_db()->prepare('SELECT COUNT(*) FROM project_milestones WHERE id=? AND project_id=?');$milestoneCheck->execute([$milestoneId,$id]);if((int)$milestoneCheck->fetchColumn()<1)throw new RuntimeException('milestone_project_mismatch');}
            $itemType=in_array(vp3_input('item_type'),['task_group','milestone','content','asset','review','launch_gate','risk'],true)?vp3_input('item_type'):'task_group';
            $ownerType=in_array(vp3_input('owner_type'),['vp3','customer','shared','external'],true)?vp3_input('owner_type'):'shared';
            vp3_db()->prepare("INSERT INTO production_plan_items(plan_id,milestone_id,title,description,item_type,target_date,owner_type,status,sort_order,created_at,updated_at) VALUES (?,NULLIF(?,0),?,?,?,?,?,'planned',?,NOW(),NOW())")
                ->execute([$planId,$milestoneId,vp3_text_slice($title,190),vp3_input('item_description'),$itemType,vp3_input('target_date')?:null,$ownerType,(int)vp3_input('sort_order','0')]);
        }
        vp3_flash('success','Project updated.');
    }catch(Throwable $e){vp3_flash('error',str_replace('_',' ',$e->getMessage()));}
    vp3_redirect('admin/project.php?id='.$id);
}
$customers=vp3_db()->query("SELECT id,name,email FROM customers WHERE status IN ('active','pending') ORDER BY name")->fetchAll();$admins=vp3_db()->query("SELECT id,name FROM admins WHERE status='active' ORDER BY name")->fetchAll();$creators=[];$shows=[];try{$creators=vp3_db()->query("SELECT id,display_name,customer_id FROM creators ORDER BY display_name")->fetchAll();$shows=vp3_db()->query("SELECT id,title,customer_id FROM shows ORDER BY title")->fetchAll();}catch(Throwable){}
$milestones=$tasks=$approvals=$assets=$comments=$activity=$plans=[];
if($id){
    $stmt=vp3_db()->prepare('SELECT * FROM project_milestones WHERE project_id=? ORDER BY sort_order,due_date,id');$stmt->execute([$id]);$milestones=$stmt->fetchAll();
    $stmt=vp3_db()->prepare('SELECT t.*,m.title milestone_title,a.name admin_name,c.name customer_name FROM project_tasks t LEFT JOIN project_milestones m ON m.id=t.milestone_id LEFT JOIN admins a ON a.id=t.assigned_admin_id LEFT JOIN customers c ON c.id=t.assigned_customer_id WHERE t.project_id=? ORDER BY FIELD(t.status,\'in_progress\',\'ready\',\'waiting\',\'review\',\'backlog\',\'completed\',\'cancelled\'),t.due_at');$stmt->execute([$id]);$tasks=$stmt->fetchAll();
    $stmt=vp3_db()->prepare('SELECT pa.*,a.title asset_title,t.title task_title FROM project_approvals pa LEFT JOIN project_assets a ON a.id=pa.asset_id LEFT JOIN project_tasks t ON t.id=pa.task_id WHERE pa.project_id=? ORDER BY FIELD(pa.status,\'pending\',\'revision_requested\',\'approved\',\'rejected\',\'cancelled\'),pa.created_at DESC');$stmt->execute([$id]);$approvals=$stmt->fetchAll();
    $stmt=vp3_db()->prepare("SELECT * FROM project_assets WHERE project_id=? AND status='active' ORDER BY updated_at DESC");$stmt->execute([$id]);$assets=$stmt->fetchAll();
    $stmt=vp3_db()->prepare('SELECT pc.*,a.name admin_name,c.name customer_name FROM project_comments pc LEFT JOIN admins a ON pc.author_type=\'admin\' AND a.id=pc.author_id LEFT JOIN customers c ON pc.author_type=\'customer\' AND c.id=pc.author_id WHERE pc.project_id=? ORDER BY pc.created_at DESC LIMIT 100');$stmt->execute([$id]);$comments=$stmt->fetchAll();
    $stmt=vp3_db()->prepare('SELECT * FROM project_activity WHERE project_id=? ORDER BY created_at DESC LIMIT 100');$stmt->execute([$id]);$activity=$stmt->fetchAll();
    $stmt=vp3_db()->prepare('SELECT pp.*,(SELECT COUNT(*) FROM production_plan_items ppi WHERE ppi.plan_id=pp.id) item_count FROM production_plans pp WHERE pp.project_id=? ORDER BY version_number DESC');$stmt->execute([$id]);$plans=$stmt->fetchAll();
    $stmt=vp3_db()->prepare('SELECT p.*,c.name customer_name,c.email customer_email FROM creative_projects p JOIN customers c ON c.id=p.customer_id WHERE p.id=?');$stmt->execute([$id]);$row=$stmt->fetch();
}
$pageTitle=$row?'Project · '.$row['title']:'Create Project';require VP3_ROOT.'/includes/admin-header.php';?>
<div class="admin-page-head"><div><span class="admin-kicker">Creative operations</span><h1><?=vp3_e($pageTitle)?></h1><?php if($row):?><p><?=vp3_e($row['customer_name'].' · '.$row['customer_email'])?></p><?php endif;?></div><a class="button secondary" href="projects.php">Back to projects</a></div>
<form class="card admin-form" method="post">
<?=vp3_csrf_field()?>
<input type="hidden" name="action" value="save">
<?php if(!$id && !empty($prefill['brief_id'])):?><input type="hidden" name="brief_id" value="<?=(int)$prefill['brief_id']?>"><?php endif;?>
<div class="admin-form-grid">
<?php if(!$id):?><div class="field"><label>Customer</label><select name="customer_id" required><option value="">Select</option><?php foreach($customers as $c):?><option value="<?=(int)$c['id']?>" <?=(int)($prefill['customer_id']??0)===(int)$c['id']?'selected':''?>><?=vp3_e($c['name'].' · '.$c['email'])?></option><?php endforeach;?></select></div><?php endif;?>
<div class="field"><label>Title</label><input name="title" required value="<?=vp3_e($row['title']??$prefill['title']??'')?>"></div>
<div class="field"><label>Project type</label><input name="project_type" value="<?=vp3_e($row['project_type']??'media_platform')?>"></div>
<div class="field"><label>Project manager</label><select name="project_manager_admin_id"><option value="0">Unassigned</option><?php foreach($admins as $a):?><option value="<?=(int)$a['id']?>" <?=(int)($row['project_manager_admin_id']??$admin['id'])===(int)$a['id']?'selected':''?>><?=vp3_e($a['name'])?></option><?php endforeach;?></select></div>
<div class="field"><label>Creator</label><select name="creator_id"><option value="0">None</option><?php foreach($creators as $c):?><option value="<?=(int)$c['id']?>" <?=(int)($row['creator_id']??0)===(int)$c['id']?'selected':''?>><?=vp3_e($c['display_name'])?></option><?php endforeach;?></select></div>
<div class="field"><label>Show</label><select name="show_id"><option value="0">None</option><?php foreach($shows as $show):?><option value="<?=(int)$show['id']?>" <?=(int)($row['show_id']??0)===(int)$show['id']?'selected':''?>><?=vp3_e($show['title'])?></option><?php endforeach;?></select></div>
<div class="field"><label>Phase</label><select name="phase"><?php foreach(['discovery','strategy','development','production','launch','active','paused','completed','cancelled'] as $v):?><option <?=($row['phase']??'discovery')===$v?'selected':''?>><?=$v?></option><?php endforeach;?></select></div>
<div class="field"><label>Health</label><select name="health_status"><?php foreach(['on_track','at_risk','blocked','complete'] as $v):?><option <?=($row['health_status']??'on_track')===$v?'selected':''?>><?=$v?></option><?php endforeach;?></select></div>
<div class="field"><label>Status</label><select name="status"><?php foreach(['draft','active','paused','completed','archived'] as $v):?><option <?=($row['status']??'active')===$v?'selected':''?>><?=$v?></option><?php endforeach;?></select></div>
<div class="field"><label>Target launch</label><input type="date" name="target_launch_date" value="<?=vp3_e($row['target_launch_date']??$prefill['target_launch_date']??'')?>"></div>
<div class="field"><label>Actual launch</label><input type="date" name="actual_launch_date" value="<?=vp3_e($row['actual_launch_date']??'')?>"></div>
<div class="field full"><label>Summary</label><textarea name="summary"><?=vp3_e($row['summary']??$prefill['summary']??'')?></textarea></div>
</div><button class="button"><?= $id?'Save project':'Create project' ?></button></form>
<?php if($id):?><div class="project-ops-summary"><div class="stat"><span>Readiness</span><strong><?=(int)$row['readiness_percent']?>%</strong></div><div class="stat"><span>Open tasks</span><strong><?=count(array_filter($tasks,fn($t)=>!in_array($t['status'],['completed','cancelled'],true)))?></strong></div><div class="stat"><span>Pending approvals</span><strong><?=count(array_filter($approvals,fn($a)=>$a['status']==='pending'))?></strong></div><div class="stat"><span>Assets</span><strong><?=count($assets)?></strong></div></div>
<section class="admin-section admin-split"><div><h2>Milestones</h2><div class="activity-list"><?php foreach($milestones as $m):?><article><strong><?=vp3_e($m['title'])?></strong><span><?=vp3_e($m['status'].' · '.($m['due_date']?:'No date'))?></span><p><?=vp3_e($m['description'])?></p><form class="inline-status-form" method="post"><?=vp3_csrf_field()?><input type="hidden" name="action" value="milestone_update"><input type="hidden" name="milestone_id" value="<?=(int)$m['id']?>"><select name="status"><?php foreach(['planned','active','at_risk','blocked','completed','cancelled'] as $status):?><option <?=$m['status']===$status?'selected':''?>><?=$status?></option><?php endforeach;?></select><button class="button tiny secondary">Update</button></form></article><?php endforeach;?></div></div><form class="card" method="post"><?=vp3_csrf_field()?><input type="hidden" name="action" value="milestone"><h3>Add milestone</h3><div class="field"><label>Title</label><input name="title" required></div><div class="field"><label>Description</label><textarea name="description"></textarea></div><div class="field"><label>Phase</label><input name="phase"></div><div class="field"><label>Due date</label><input name="due_date" type="date"></div><div class="field"><label>Status</label><select name="status"><option>planned</option><option>active</option><option>at_risk</option><option>blocked</option><option>completed</option></select></div><button class="button small">Add milestone</button></form></section>
<section class="admin-section"><div class="section-heading"><div><h2>Tasks</h2></div></div><div class="task-list"><?php foreach($tasks as $t):?><article class="task-row <?=vp3_e(vp3_due_state($t['due_at']))?>"><div><span class="badge <?=vp3_e($t['status'])?>"><?=vp3_e($t['status'])?></span><h3><?=vp3_e($t['title'])?></h3><p><?=vp3_e($t['description'])?></p><small><?=vp3_e(($t['milestone_title']?:'General').' · '.($t['admin_name']?:$t['customer_name']?:'Unassigned').' · '.($t['due_at']?:'No date'))?></small></div><form class="inline-status-form" method="post"><?=vp3_csrf_field()?><input type="hidden" name="action" value="task_update"><input type="hidden" name="task_id" value="<?=(int)$t['id']?>"><select name="status"><?php foreach(['backlog','ready','in_progress','waiting','review','completed','cancelled'] as $status):?><option <?=$t['status']===$status?'selected':''?>><?=$status?></option><?php endforeach;?></select><button class="button tiny secondary">Update</button></form></article><?php endforeach;?></div><form class="card admin-form admin-section" method="post"><?=vp3_csrf_field()?><input type="hidden" name="action" value="task"><h3>Add task</h3><div class="admin-form-grid"><div class="field"><label>Title</label><input name="title" required></div><div class="field"><label>Milestone</label><select name="milestone_id"><option value="0">General</option><?php foreach($milestones as $m):?><option value="<?=(int)$m['id']?>"><?=vp3_e($m['title'])?></option><?php endforeach;?></select></div><div class="field full"><label>Description</label><textarea name="description"></textarea></div><div class="field"><label>Assignment</label><select name="assignment"><option value="vp3">VP3</option><option value="customer">Customer</option></select></div><div class="field"><label>Assigned VP3 staff</label><select name="assigned_admin_id"><option value="<?=(int)$admin['id']?>">Current admin</option><?php foreach($admins as $a):?><option value="<?=(int)$a['id']?>"><?=vp3_e($a['name'])?></option><?php endforeach;?></select></div><div class="field"><label>Type</label><input name="task_type" value="general"></div><div class="field"><label>Priority</label><select name="priority"><option>normal</option><option>low</option><option>high</option><option>urgent</option></select></div><div class="field"><label>Status</label><select name="status"><option>ready</option><option>backlog</option><option>in_progress</option><option>waiting</option><option>review</option></select></div><div class="field"><label>Due</label><input type="datetime-local" name="due_at"></div><div class="field"><label>Estimated minutes</label><input type="number" min="0" name="estimated_minutes"></div></div><button class="button small">Add task</button></form></section>
<section class="admin-section admin-split"><div><h2>Approvals</h2><div class="activity-list"><?php foreach($approvals as $a):?><article><strong><?=vp3_e($a['title'])?></strong><span><?=vp3_e($a['status'].' · '.($a['task_title']?:$a['asset_title']?:'Item'))?></span><p><?=vp3_e($a['response_notes']?:$a['instructions'])?></p></article><?php endforeach;?></div></div><form class="card" method="post"><?=vp3_csrf_field()?><input type="hidden" name="action" value="approval"><h3>Request approval</h3><div class="field"><label>Title</label><input name="title" required></div><div class="field"><label>Task</label><select name="task_id"><option value="0">None</option><?php foreach($tasks as $t):?><option value="<?=(int)$t['id']?>"><?=vp3_e($t['title'])?></option><?php endforeach;?></select></div><div class="field"><label>Asset</label><select name="asset_id"><option value="0">None</option><?php foreach($assets as $a):?><option value="<?=(int)$a['id']?>"><?=vp3_e($a['title'])?></option><?php endforeach;?></select></div><div class="field"><label>Instructions</label><textarea name="instructions"></textarea></div><div class="field"><label>Due</label><input name="due_at" type="datetime-local"></div><button class="button small">Request approval</button></form></section>
<section class="admin-section admin-split"><div><h2>Assets</h2><div class="asset-grid"><?php foreach($assets as $a):?><article class="asset-card"><span><?=vp3_e($a['category'].' · '.$a['visibility'])?></span><h3><?=vp3_e($a['title'])?></h3><p><?=vp3_e($a['description'])?></p><small><?=vp3_e($a['approval_status'])?></small></article><?php endforeach;?></div></div><form class="card" method="post"><?=vp3_csrf_field()?><input type="hidden" name="action" value="asset"><h3>Register asset</h3><div class="field"><label>Title</label><input name="asset_title" required></div><div class="field"><label>Category</label><select name="category"><option>general</option><option>brand</option><option>artwork</option><option>audio</option><option>video</option><option>script</option><option>contract</option><option>launch</option></select></div><div class="field"><label>HTTPS URL</label><input name="external_url" type="url" required></div><div class="field"><label>Description</label><textarea name="asset_description"></textarea></div><div class="field"><label>Visibility</label><select name="visibility"><option>shared</option><option>internal</option><option>customer</option></select></div><div class="field"><label>Approval status</label><select name="approval_status"><option>not_required</option><option>pending</option><option>approved</option><option>revision_requested</option></select></div><button class="button small">Register asset</button></form></section>
<section class="admin-section admin-split"><div><h2>Production plans</h2><?php foreach($plans as $p):?><article class="card"><span class="badge <?=vp3_e($p['status'])?>"><?=vp3_e($p['status'])?></span><h3><?=vp3_e($p['title'])?></h3><p><?=vp3_e($p['objective'])?></p><small>Version <?=(int)$p['version_number']?> · <?=(int)$p['item_count']?> items</small></article><?php endforeach;?></div><div><form class="card" method="post"><?=vp3_csrf_field()?><input type="hidden" name="action" value="production_plan"><h3>Create production plan</h3><div class="field"><label>Title</label><input name="plan_title" required></div><div class="field"><label>Objective</label><textarea name="objective"></textarea></div><button class="button small">Create draft plan</button></form><?php if($plans):?><form class="card admin-section" method="post"><?=vp3_csrf_field()?><input type="hidden" name="action" value="plan_item"><h3>Add plan item</h3><div class="field"><label>Plan</label><select name="plan_id"><?php foreach($plans as $p):?><option value="<?=(int)$p['id']?>"><?=vp3_e($p['title'])?></option><?php endforeach;?></select></div><div class="field"><label>Milestone</label><select name="milestone_id"><option value="0">None</option><?php foreach($milestones as $m):?><option value="<?=(int)$m['id']?>"><?=vp3_e($m['title'])?></option><?php endforeach;?></select></div><div class="field"><label>Title</label><input name="item_title" required></div><div class="field"><label>Description</label><textarea name="item_description"></textarea></div><div class="field"><label>Type</label><select name="item_type"><option>task_group</option><option>milestone</option><option>content</option><option>asset</option><option>review</option><option>launch_gate</option><option>risk</option></select></div><div class="field"><label>Owner</label><select name="owner_type"><option>shared</option><option>vp3</option><option>customer</option><option>external</option></select></div><div class="field"><label>Target date</label><input name="target_date" type="date"></div><button class="button small">Add plan item</button></form><?php endif;?></div></section>
<section class="admin-section admin-split"><div><h2>Comments</h2><form class="card" method="post"><?=vp3_csrf_field()?><input type="hidden" name="action" value="comment"><div class="field"><label>Comment</label><textarea name="comment" required></textarea></div><div class="field"><label>Visibility</label><select name="visibility"><option>shared</option><option>internal</option><option>customer</option></select></div><button class="button small">Post comment</button></form><div class="activity-list"><?php foreach($comments as $c):?><article><strong><?=vp3_e($c['admin_name']?:$c['customer_name']?:ucfirst($c['author_type']))?></strong><span><?=vp3_e($c['visibility'].' · '.$c['created_at'])?></span><p><?=nl2br(vp3_e($c['comment']))?></p></article><?php endforeach;?></div></div><div><h2>Activity</h2><div class="activity-list"><?php foreach($activity as $a):?><article><strong><?=vp3_e($a['summary'])?></strong><span><?=vp3_e($a['actor_type'].' · '.$a['created_at'])?></span></article><?php endforeach;?></div></div></section><?php endif;?>
<?php require VP3_ROOT.'/includes/admin-footer.php';?>
