<?php
declare(strict_types=1);
require dirname(__DIR__) . '/bootstrap.php';
vp3_require_admin_permission('network.view');
$pageTitle='Public Platforms';require VP3_ROOT.'/includes/admin-header.php';
$rows=vp3_db()->query("SELECT ppl.id,ppl.display_name,ppl.slug,ppl.public_domain,ppl.hosting_type,ppl.verification_id,ppl.verification_status,ppl.listing_status,ppl.auto_publish_clips,ppl.featured_rank,p.name product_name,l.edition,c.name customer_name FROM public_platform_listings ppl JOIN products p ON p.id=ppl.product_id JOIN licenses l ON l.id=ppl.license_id JOIN customers c ON c.id=ppl.customer_id ORDER BY ppl.featured_rank>0 DESC,ppl.featured_rank ASC,ppl.id DESC LIMIT 250")->fetchAll();
?>
<div class="admin-page-head"><div><span class="admin-kicker">VP3 Network</span><h1>Public platforms</h1><p>Safe public records connect licensed platforms to creators, shows, domains, and clip syndication.</p></div><?php if(vp3_admin_can($admin,'network.manage')):?><a class="button" href="public-listing.php">Register platform</a><?php endif;?></div><div class="table-wrap"><table class="table"><thead><tr><th>Platform</th><th>Customer</th><th>Product</th><th>Domain</th><th>Verification ID</th><th>Status</th><th>Clips</th><th></th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><b><?=vp3_e($row['display_name'])?></b><br><small><?=vp3_e($row['hosting_type'])?></small></td><td><?=vp3_e($row['customer_name'])?></td><td><?=vp3_e($row['product_name'].' · '.$row['edition'])?></td><td><?=vp3_e($row['public_domain'])?></td><td><code><?=vp3_e($row['verification_id'])?></code></td><td><span class="badge <?=vp3_e($row['verification_status'])?>"><?=vp3_e($row['verification_status'])?></span><br><small><?=vp3_e($row['listing_status'])?></small></td><td><?=$row['auto_publish_clips']?'Auto-approved':'Moderated'?></td><td><a href="public-listing.php?id=<?=(int)$row['id']?>">Open</a></td></tr><?php endforeach;?></tbody></table></div>
<?php require VP3_ROOT.'/includes/admin-footer.php';?>
